"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/reactive-element.cjs");const c=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/lit-html.cjs");require("../node_modules/.pnpm/lit-element@4.2.2/node_modules/lit-element/lit-element.cjs");const p=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/custom-element.cjs"),n=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/property.cjs"),h=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/state.cjs"),S=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/directives/class-map.cjs"),d=require("../constants/tags.cjs"),y=require("../abstractions/igds-element.cjs");require("../abstractions/angular-form-element.cjs");const i=require("./constants.cjs"),g=require("./skeleton.scss.cjs"),v=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/css-tag.cjs");var _=Object.defineProperty,E=Object.getOwnPropertyDescriptor,r=(o,t,a,s)=>{for(var e=s>1?void 0:s?E(t,a):t,u=o.length-1,l;u>=0;u--)(l=o[u])&&(e=(s?l(t,a,e):l(e))||e);return s&&e&&_(t,a,e),e};exports.Skeleton=class extends y.IGDSElement{constructor(){super(...arguments),this.variant=i.IGDS_SKELETON_VARIANT.rectangular,this.radius=16,this.width="100%",this.currentWidth=this.width,this.currentHeight=this.height}updateCurrentState(){const t=this.variant==="circle";this.currentWidth=t?`${Number(this.radius)*2}px`:this.width,this.currentHeight=t?`${Number(this.radius)*2}px`:this.height}update(t){super.update(t),this.updateCurrentState()}render(){return c.html`
      <div
        class=${S.classMap({skeleton:!0,"skeleton--circle":this.variant===i.IGDS_SKELETON_VARIANT.circle,"skeleton--rectangular":this.variant===i.IGDS_SKELETON_VARIANT.rectangular,"skeleton--title":this.variant===i.IGDS_SKELETON_VARIANT.title,"skeleton--subtitle":this.variant===i.IGDS_SKELETON_VARIANT.subtitle,"skeleton--body":this.variant===i.IGDS_SKELETON_VARIANT.body})}
        aria-hidden="true"
        aria-busy="true"
        data-variant="${this.variant}"
        style="width: ${this.currentWidth}; height: ${this.currentHeight}"
      ></div>
    `}};exports.Skeleton.styles=v.unsafeCSS(g);r([n.property({type:String})],exports.Skeleton.prototype,"variant",2);r([n.property({type:Number})],exports.Skeleton.prototype,"radius",2);r([n.property({type:String})],exports.Skeleton.prototype,"width",2);r([n.property({type:String})],exports.Skeleton.prototype,"height",2);r([h.state()],exports.Skeleton.prototype,"currentWidth",2);r([h.state()],exports.Skeleton.prototype,"currentHeight",2);exports.Skeleton=r([p.customElement(d.IGDS_TAGS.skeleton)],exports.Skeleton);
