"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/reactive-element.cjs");const c=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/lit-html.cjs");require("../node_modules/.pnpm/lit-element@4.2.2/node_modules/lit-element/lit-element.cjs");const u=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/custom-element.cjs"),a=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/property.cjs"),p=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/state.cjs"),d=require("../node_modules/.pnpm/@lit_context@1.1.6/node_modules/@lit/context/lib/decorators/provide.cjs"),m=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/directives/class-map.cjs"),g=require("../constants/events.cjs"),h=require("../constants/tags.cjs"),S=require("../abstractions/igds-element.cjs");require("../abstractions/angular-form-element.cjs");const x=require("./context.cjs"),y=require("./segmented-control.scss.cjs");require("../icon/icon.cjs");require("../button/button.cjs");require("../tooltip/tooltip.cjs");const q=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/css-tag.cjs");var C=Object.defineProperty,v=Object.getOwnPropertyDescriptor,o=(s,e,t,n)=>{for(var r=n>1?void 0:n?v(e,t):e,i=s.length-1,l;i>=0;i--)(l=s[i])&&(r=(n?l(e,t,r):l(r))||r);return n&&r&&C(e,t,r),r};exports.SegmentedControl=class extends S.IGDSElement{constructor(){super(),this.contextData={updateSelectedId:this.updateSelectedId.bind(this),reportAboutTextSegment:this.reportAboutTextSegment.bind(this)},this.segmentsWithText=[],this._internals=this.attachInternals()}set disabled(e){this.contextData={...this.contextData,disabled:e}}set size(e){this.contextData={...this.contextData,size:e}}get isIconOnly(){return this.segmentsWithText.every(e=>!e.hasText)}updateSelectedId(e,t){this.contextData={...this.contextData,selectedId:e},this._internals.setFormValue(e??null),!t?.skipEvent&&this.emit(g.IGDS_EVENTS.change,{id:e})}reportAboutTextSegment(e,t){this.segmentsWithText=[...this.segmentsWithText.filter(n=>n.id!==e),{id:e,hasText:t}]}render(){return c.html`
      <div
        role="group"
        aria-label="Segmented Control"
        class=${m.classMap({"segmented-control":!0,"segmented-control--icon-only":this.isIconOnly})}
      >
        <slot></slot>
      </div>
    `}};exports.SegmentedControl.styles=q.unsafeCSS(y);exports.SegmentedControl.formAssociated=!0;o([d.provide({context:x.segmentContext})],exports.SegmentedControl.prototype,"contextData",2);o([a.property({type:Boolean})],exports.SegmentedControl.prototype,"disabled",1);o([a.property({type:String})],exports.SegmentedControl.prototype,"size",1);o([a.property({type:String})],exports.SegmentedControl.prototype,"name",2);o([p.state()],exports.SegmentedControl.prototype,"segmentsWithText",2);exports.SegmentedControl=o([u.customElement(h.IGDS_TAGS.segmentedControl)],exports.SegmentedControl);
