export var IGDS_PROFILE_PICKER_SIZES;
(function (IGDS_PROFILE_PICKER_SIZES) {
    IGDS_PROFILE_PICKER_SIZES["large"] = "large";
    IGDS_PROFILE_PICKER_SIZES["small"] = "small";
})(IGDS_PROFILE_PICKER_SIZES || (IGDS_PROFILE_PICKER_SIZES = {}));
