import { PropertyValues } from 'lit';
import { AngularFormElement } from '../abstractions';
import { Option } from './option';
import { IGDS_EVENT_KEYS } from '../constants';
import { TreeNode } from './tree-view';
import '../icon/icon';
import '../input/input';
import '../button/button';
import '../checkbox/checkbox';
import { Checkbox } from '../checkbox/checkbox';
declare class Dropdown extends AngularFormElement {
    constructor();
    static formAssociated: boolean;
    static styles: import("lit").CSSResult[];
    trigger: HTMLInputElement;
    select: HTMLSelectElement;
    dropdownOptionElements: HTMLElement[];
    listElement: HTMLDivElement;
    isPopupOpen: boolean;
    noOptions: boolean;
    filterText: string;
    highlightedId: string | null;
    treeCollapsedId?: string;
    treeExpandedId?: string;
    treeFocusedIndex: number;
    valueIcon: string | null;
    label?: string;
    labelIcon?: string;
    name?: string;
    multiple: boolean;
    treeView: boolean;
    form?: string;
    selected: string[];
    defaultValue?: string;
    placeholder?: string;
    disabled: boolean;
    required: boolean;
    set options(value: Option[] | undefined);
    get options(): Option[];
    filterable: boolean;
    helpText?: string;
    helpIcon: string;
    tooltip?: string;
    tooltipQuestion?: string;
    tooltipIcon?: boolean;
    invalid: boolean;
    error?: string;
    dir: string;
    onChange?: ((event: Event) => void) | null;
    treeNodes?: TreeNode[];
    private _internals;
    private _options;
    private _scrollHandler;
    connectedCallback(): void;
    handleDocumentMouseDown: (event: MouseEvent) => void;
    firstUpdated(): void;
    updated(changedProperties: PropertyValues<this>): void;
    private resizeHandler;
    private handleSelectedChange;
    setSelectedOptions(): void;
    setMultiSelectedOptions(): void;
    private clearSingleSelectionState;
    private syncSelectElementToOption;
    setSingleSelectedOption(): void;
    setTreeViewSelectedNode(): void;
    private findNodeById;
    onClearFilter(): void;
    disconnectedCallback(): void;
    private startScrollListener;
    private stopScrollListener;
    isExtraDoublePaddingLtr(): boolean | "";
    isExtraDoublePaddingRtr(): boolean | "";
    render(): import("lit").TemplateResult<1>;
    getInputValueIcon(): import("lit").TemplateResult<1>;
    getClearIcon(): import("lit").TemplateResult<1>;
    onClear(): void;
    onClearIconKeyDown(event: KeyboardEvent): void;
    togglePopup(): void;
    removeHighlightedClass(): void;
    onKeyDown(event: KeyboardEvent): void;
    processOptionIndex(options: HTMLElement[]): void;
    private selectHighlightedOption;
    private handleEnterOrHighlightedSpace;
    private handleSpaceWithoutHighlight;
    handleEnterOrSpaceDown(key: IGDS_EVENT_KEYS, options: HTMLElement[] | null): boolean;
    handleEscapeDown(key: IGDS_EVENT_KEYS): void;
    handleArrowKeysDown(key: IGDS_EVENT_KEYS, options: HTMLElement[] | null): void;
    onKeyDownForFilterableDropdown(event: KeyboardEvent): void;
    processCheckboxChecked(checkboxElement: Checkbox, highlightedOption: HTMLElement, options: HTMLElement[]): void;
    emitComponentEvents(): void;
    handleEnterOrSpaceDownForMultipleChoicesDropdown(event: KeyboardEvent): void;
    handleArrowsDownForMultipleChoiceDropdown(key: IGDS_EVENT_KEYS): void;
    onKeyDownForMultipleChoicesDropdown(event: KeyboardEvent): void;
    handleEnterOrSpaceDownForTreeViewDropdown(event: KeyboardEvent): void;
    onKeyDownForTreeViewDropdown(event: KeyboardEvent): void;
    scrollToIndexWhenMoveDown(index: number): void;
    scrollToIndexWhenMoveUp(index: number): void;
    handleEnterOrSpaceDownForSingleChoiceDropdown(key: IGDS_EVENT_KEYS): void;
    findSingleChoiceIndex(options: HTMLElement[], key: IGDS_EVENT_KEYS): number;
    processSingleChoiceDropdownOptions(options: HTMLElement[], index: number): void;
    handleArrowsDownForSingleChoiceDropdown(key: IGDS_EVENT_KEYS): void;
    onKeyDownForSingleChoiceDropdown(event: KeyboardEvent): void;
    setPopupPosition(): Promise<void>;
    setPopupPositionWhenOpen(): void;
    getDropdownOptions(): HTMLElement[] | null;
    setFilterText(event: CustomEvent): void;
    onBlur(event: CustomEvent): void;
    onFocus(event: CustomEvent): void;
    onChangeHandler(event: Event): void;
    private calculateIndexIncrement;
    getPopupActions(): import("lit").TemplateResult<1>;
    selectAllHandler(): void;
    getFormValue(value: string | string[]): FormData | string;
    resetAllHandler(): void;
    renderDropdownOptions(): import("lit").TemplateResult<1>;
    renderDropdownTreeView(): import("lit").TemplateResult<1>;
    renderNoOptions(): import("lit").TemplateResult<1>;
    getOptions(): Option[];
    get filteredOptions(): Option[];
    onSelect(option: Option, index: number): void;
    onMultiSelect(option: Option, index: number): void;
    setFormValue(value?: string | null): void;
    onSingleSelect(option: Option, index: number): void;
    onTreeNodeClick(event: CustomEvent): void;
    onTreeNodeFocusChanged(event: CustomEvent): void;
    resetTreeCollapsedIds(): void;
    getError(): import("lit").TemplateResult<1>;
    getHelpContainer(): import("lit").TemplateResult<1>;
    getHelpIcon(): import("lit").TemplateResult<1>;
    getHelpText(): import("lit").TemplateResult<1>;
}
export { Dropdown };
declare global {
    interface HTMLElementTagNameMap {
        'igds-dropdown': Dropdown;
    }
}
