import { PropertyValues } from 'lit';
import { AngularFormElement } from '../abstractions';
import { IGDS_INPUT_AUTOCAPITALIZE_OPTIONS, IGDS_INPUT_TYPES, IGDS_TEXTAREA_SIZES } from './constants';
import '../icon';
import '../error-box/default-error-box';
declare class Input extends AngularFormElement {
    static formAssociated: boolean;
    static styles: import("lit").CSSResult;
    private _internals;
    componentId: string;
    dir: string;
    type: `${IGDS_INPUT_TYPES}`;
    label?: string;
    labelIcon?: string;
    name?: string;
    form?: string;
    defaultValue?: string;
    placeholder?: string;
    disabled: boolean;
    required: boolean;
    readonly: boolean;
    rows?: number;
    cols?: number;
    min?: number;
    max?: number;
    pattern?: string;
    maxlength?: number;
    icon: string | null;
    iconPosition?: string;
    helpText?: string;
    helpIcon: string;
    tooltip?: string;
    tooltipQuestion?: string;
    tooltipIcon?: boolean;
    invalid: boolean;
    error?: string;
    autoFocus?: boolean;
    autoComplete: 'on' | 'off';
    autoCapitalize: `${IGDS_INPUT_AUTOCAPITALIZE_OPTIONS}`;
    autocorrect: boolean;
    autoHeight?: boolean;
    step?: number;
    size: `${IGDS_TEXTAREA_SIZES}`;
    onChange?: ((event: Event) => void) | null;
    private readonly input;
    private readonly textarea;
    get validity(): ValidityState;
    checkValidity(): boolean;
    reportValidity(): boolean;
    constructor();
    protected firstUpdated(changedProperties: PropertyValues<this>): void;
    updated(changedProperties: PropertyValues<this>): void;
    getTopBox(): import("lit").TemplateResult<1> | undefined;
    getInputLabel(): import("lit").TemplateResult<1> | undefined;
    getTooltipIcon(): import("lit").TemplateResult<1> | undefined;
    getTooltipQuestion(): import("lit").TemplateResult<1> | undefined;
    onInput(event: Event): void;
    private applyInternalInputValidityOnComponent;
    onChangeHandler(event: Event): void;
    onBlur(event: Event): void;
    onFocus(event: Event): void;
    updateTextareaHeight(): void;
    getTextareaCssClass(): import("lit/async-directive.js").DirectiveResult<typeof import("lit/directives/class-map.js").ClassMapDirective>;
    getInputCssClass(): import("lit/async-directive.js").DirectiveResult<typeof import("lit/directives/class-map.js").ClassMapDirective>;
    getInputBox(): import("lit").TemplateResult<1>;
    getRows(): number | undefined;
    getMaxLengthContainer(): import("lit").TemplateResult<1> | undefined;
    getMaxLengthContainerContent(): string;
    padDigit(digit: number): string;
    getHelpIcon(): import("lit").TemplateResult<1>;
    getHelpText(): import("lit").TemplateResult<1> | undefined;
    getHelpBox(): import("lit").TemplateResult<1> | undefined;
    getError(): import("lit").TemplateResult<1> | undefined;
    render(): import("lit").TemplateResult<1>;
    getInputIconCssClass(): import("lit/async-directive.js").DirectiveResult<typeof import("lit/directives/class-map.js").ClassMapDirective>;
    getInputIcon(): import("lit").TemplateResult<1> | undefined;
    getIconAriaLabel(): "Date picker icon" | "Text cell icon" | "Search icon" | "Input icon" | undefined;
    getIconTabIndex(): number | undefined;
    onIconClick(): void;
    onIconKeyDown(event: KeyboardEvent): void;
}
export { Input };
declare global {
    interface HTMLElementTagNameMap {
        'igds-input': Input;
    }
}
