"use strict";Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"});require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/reactive-element.cjs");const l=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/lit-html.cjs");require("../node_modules/.pnpm/lit-element@4.2.2/node_modules/lit-element/lit-element.cjs");const m=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/custom-element.cjs"),u=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/property.cjs"),g=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/state.cjs"),c=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/decorators/query.cjs"),p=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/directives/class-map.cjs"),d=require("../constants/tags.cjs"),H=require("../abstractions/igds-element.cjs");require("../abstractions/angular-form-element.cjs");const o=require("../node_modules/.pnpm/lit-html@3.3.2/node_modules/lit-html/directives/style-map.cjs"),y=require("./animate-height.scss.cjs"),T=require("../node_modules/.pnpm/@lit_reactive-element@2.1.2/node_modules/@lit/reactive-element/css-tag.cjs");var f=Object.defineProperty,A=Object.getOwnPropertyDescriptor,a=(h,e,s,t)=>{for(var i=t>1?void 0:t?A(e,s):e,r=h.length-1,n;r>=0;r--)(n=h[r])&&(i=(t?n(e,s,i):n(i))||i);return t&&i&&f(e,s,i),i};exports.AnimateHeight=class extends H.IGDSElement{constructor(){super(),this._expand=!1,this.startTime=0,this.fullTargetHeight=0,this.actualTargetHeight=0,this.residualDuration=0,this.duration=200,this.height=0,this.isAutoHeight=!1,this.animateIt=this.animateIt.bind(this)}set expand(e){this._expand=e,setTimeout(()=>{this.animationId&&cancelAnimationFrame(this.animationId),this.animateHeight()})}get expand(){return this._expand}animateHeight(){this.startTime=performance.now(),this.fullTargetHeight=this.container.scrollHeight,this.actualTargetHeight=this.height,this.residualDuration=this.expand?this.duration*(1-this.actualTargetHeight/this.fullTargetHeight):this.duration*(this.actualTargetHeight/this.fullTargetHeight),this.animationId=requestAnimationFrame(this.animateIt),this.isAutoHeight=!1}animateIt(){const s=performance.now()-this.startTime,t=Math.min(s/this.residualDuration,1);this.expand?this.height=this.actualTargetHeight+t*(this.fullTargetHeight-this.actualTargetHeight):this.height=this.actualTargetHeight-this.actualTargetHeight*t,t<1?this.animationId=requestAnimationFrame(this.animateIt):this.expand?this.isAutoHeight=!0:this.height=0}render(){return l.html`
      <section
        class="animate-height"
        style=${o.styleMap({height:this.isAutoHeight?"auto":`${this.height}px`})}
      >
        <div
          class=${p.classMap({"animate-height__body":!0,"animate-height__body--visible":this.expand})}
          style=${o.styleMap({transitionDuration:`${this.duration}ms`})}
        >
          <div
            style=${o.styleMap({display:this.height===0&&!this.expand?"none":"block"})}
          >
            <slot></slot>
          </div>
        </div>
      </section>
    `}};exports.AnimateHeight.styles=T.unsafeCSS(y);a([u.property({type:Number})],exports.AnimateHeight.prototype,"duration",2);a([u.property({type:Boolean,reflect:!0})],exports.AnimateHeight.prototype,"expand",1);a([g.state()],exports.AnimateHeight.prototype,"height",2);a([g.state()],exports.AnimateHeight.prototype,"isAutoHeight",2);a([c.query(".animate-height__body")],exports.AnimateHeight.prototype,"container",2);exports.AnimateHeight=a([m.customElement(d.IGDS_TAGS.animateHeight)],exports.AnimateHeight);
