import { PropertyValues } from 'lit';
import { IGDS_TAGS } from '../constants';
import { AngularFormElement } from '../abstractions';
import { IgdsRichTextEditorContext } from './rich-text-editor-context';
import '../icon';
import '../tooltip';
import '../error-box/default-error-box';
import './editor-toolbar';
import './toolbar-item';
declare class RichTextEditor extends AngularFormElement {
    static formAssociated: boolean;
    private _internals;
    private quill;
    private quillEditor;
    private uniqueId;
    private labelId;
    private quillId;
    private inputHelpMessageId;
    private errorId;
    label?: string;
    name?: string;
    form?: string;
    defaultValue?: string;
    placeholder?: string;
    disabled: boolean;
    required: boolean;
    readonly: boolean;
    helpText?: string;
    helpIcon: string;
    tooltipIcon?: string;
    tooltipQuestion?: string;
    tooltipAnswer?: string;
    invalid: boolean;
    error?: string;
    autoFocus?: boolean;
    onChange?: ((event: Event) => void) | null;
    maxHeight?: string;
    isFocused: boolean;
    customEditorTextDirection: 'rtl' | 'ltr' | undefined;
    quillElement: HTMLDivElement;
    toolbarContainer: HTMLDivElement;
    private readonly input;
    context: IgdsRichTextEditorContext;
    get validity(): ValidityState;
    checkValidity(): boolean;
    reportValidity(): boolean;
    transformText(transformation: 'bold' | 'italic' | 'underline' | 'strike'): void;
    makeList(listType: 'ordered' | 'bullet'): void;
    makeIndent(direction: 'increase' | 'decrease'): void;
    changeTextDirection(command: 'rtl' | 'ltr'): void;
    onInput(): void;
    private applyInternalInputValidityOnComponent;
    private isEmptyValue;
    onFocus(): void;
    onBlur(): void;
    emulateChangeEvent(): void;
    onChangeHandler(event: Event): void;
    handleToolbarClick(e: Event): void;
    initToolbarSlot(): void;
    constructor();
    protected createRenderRoot(): this;
    connectedCallback(): void;
    protected firstUpdated(_changedProperties: PropertyValues): void;
    protected updated(_changedProperties: PropertyValues): void;
    disconnectedCallback(): void;
    get editorMaxHeight(): string | undefined;
    renderHeader(): import("lit").TemplateResult<1>;
    renderToolbar(): import("lit").TemplateResult<1>;
    renderEditor(): import("lit").TemplateResult<1>;
    renderHelpText(): import("lit").TemplateResult<1> | undefined;
    renderError(): import("lit").TemplateResult<1> | undefined;
    render(): import("lit").TemplateResult<1>;
}
export { RichTextEditor };
declare global {
    interface HTMLElementTagNameMap {
        [IGDS_TAGS.richTextEditor]: RichTextEditor;
    }
}
