import { PropertyValues } from 'lit';
import { AngularFormElement } from '../abstractions';
import { IGDS_TAGS } from '../constants';
import { Day, IGDS_DATE_MODE, IGDS_MONTHS, IGDS_START_WEEK_ON, IGDS_WEEK_DAYS_SHORTCUTS } from './constants';
declare class DatePicker extends AngularFormElement {
    private CSS_QUERY;
    private readonly _mediaQueryObserver;
    static styles: import("lit").CSSResult[];
    static formAssociated: boolean;
    dir: string;
    label: string;
    labelIcon?: string;
    name?: string;
    form?: string;
    defaultValue?: string;
    dateFormat?: string;
    disabled: boolean;
    required: boolean;
    readonly: boolean;
    min: string | null;
    max: string | null;
    placeholder?: string;
    withoutCalendar: boolean;
    startWeekOn: `${IGDS_START_WEEK_ON}`;
    invalid: boolean;
    error?: string;
    withIcon: boolean;
    autoFocus: boolean;
    autocomplete: 'on' | 'off';
    openOnFocus: boolean;
    autocorrect: boolean;
    onChange?: ((event: Event) => void) | null;
    isPopupOpen: boolean;
    selectedMonth: number;
    selectedYear: number;
    days: Array<Day>;
    mode: `${IGDS_DATE_MODE}`;
    yearRange: number[];
    focusedDate: number | null;
    focusedMonth: number | null;
    inputElement: HTMLInputElement;
    datePicker: HTMLInputElement;
    private _internals;
    private isMobile;
    constructor();
    protected firstUpdated(changedProperties: PropertyValues): void;
    updated(changedProperties: PropertyValues): void;
    generateCalendar(): void;
    private dayIsDisabled;
    generateYearRange(startYear: number): number[];
    disconnectedCallback(): void;
    private _scrollHandler;
    private startScrollListener;
    private stopScrollListener;
    render(): import("lit").TemplateResult<1>;
    togglePopup(): void;
    setPopupPosition(): Promise<void>;
    private setPopupPositionWhenOpen;
    onInputChange(event: CustomEvent): void;
    private clearValue;
    setValues(value: string): void;
    isValidDate(dateString: string): boolean;
    isValidDateWithoutCalendar(dateString: string): boolean;
    onInputFocus(): void;
    onInputBlur(): void;
    onInputKeyDown(event: KeyboardEvent): void;
    onChangeHandler(event: Event): void;
    handleDocumentMouseDown(event: MouseEvent): void;
    private resizeHandler;
    getError(): import("lit").TemplateResult<1>;
    renderPopup(): import("lit").TemplateResult<1>;
    onNextButtonClick(): void;
    moveToNextMonth(): void;
    openMonthPicker(): void;
    getCurrentMonth(): IGDS_MONTHS;
    openYearPicker(): void;
    onPreviousButtonClick(): void;
    moveToPreviousMonth(): void;
    onDatePickerKeyDown(event: KeyboardEvent, isDisabled: boolean): void;
    moveFocus(offset: number): void;
    onMonthPickerKeyDown(event: KeyboardEvent): void;
    moveMonthPickerFocusLeft(): void;
    moveMonthPickerFocusRight(): void;
    moveMonthPickerFocusDown(): void;
    moveMonthPickerFocusUp(): void;
    onYearPickerKeyDown(event: KeyboardEvent): void;
    focusedYear: number | null;
    moveYearPickerFocusDown(): void;
    moveYearPickerFocusUp(): void;
    moveYearPickerFocusLeft(): void;
    moveYearPickerFocusRight(): void;
    renderPicker(): import("lit").TemplateResult<1>;
    renderDatePicker(): import("lit").TemplateResult<1>;
    getWeekDayShortcuts(): typeof IGDS_WEEK_DAYS_SHORTCUTS | {
        [k: string]: IGDS_WEEK_DAYS_SHORTCUTS;
    };
    isToday(day: number): boolean;
    get todayDay(): number;
    get todayMonth(): number;
    get todayYear(): number;
    get minDate(): Date | null;
    get maxDate(): Date | null;
    get minMonth(): number | null;
    get maxMonth(): number | null;
    get minYear(): number | null;
    get maxYear(): number | null;
    isDateSelected(calendarDay: number): boolean;
    onSelectDay(day: number, isDisabled?: boolean): void;
    padNumber(number: number): string;
    renderMonthsPicker(): import("lit").TemplateResult<1>;
    onMonthChange(index: number): void;
    private commitMonthSelection;
    renderYearPicker(): import("lit").TemplateResult<1>;
    onYearChange(year: number): void;
}
export { DatePicker };
declare global {
    interface HTMLElementTagNameMap {
        [IGDS_TAGS.datePicker]: DatePicker;
    }
}
