export var IGDS_STEP_INDICATOR_ORIENTATION;
(function (IGDS_STEP_INDICATOR_ORIENTATION) {
    IGDS_STEP_INDICATOR_ORIENTATION["horizontal"] = "horizontal";
    IGDS_STEP_INDICATOR_ORIENTATION["vertical"] = "vertical";
})(IGDS_STEP_INDICATOR_ORIENTATION || (IGDS_STEP_INDICATOR_ORIENTATION = {}));
export const MAX_HORIZONTAL_STEPS = 5;
