import { DirectiveResult } from 'lit/async-directive.js';
import { ClassMapDirective } from 'lit/directives/class-map.js';
import { IGDSElement } from '../abstractions';
import { Suggestion } from './suggestion';
import { IGDS_EVENT_KEYS } from '../constants';
import { IGDS_SEARCH_FIELD_VARIANTS } from './constants';
import '../icon/icon';
import '../input/input';
import '../button/button';
import '../divider/divider';
import '../filters/filter';
import { FilterHorizontal as Filter } from '../filters';
declare class SearchField extends IGDSElement {
    constructor();
    static styles: import("lit").CSSResult[];
    searchInputElement: HTMLInputElement;
    searchGroupElement: HTMLDivElement;
    audioElement: HTMLAudioElement;
    sourceElement: HTMLSourceElement;
    searchPopupElements: HTMLElement[];
    isPopupOpen: boolean;
    isFilterPopupOpen: boolean;
    isFirstInputToggled: boolean;
    firstInputValue: string;
    lastInputValue: string;
    highlightedId: string | null;
    value: string;
    set suggestions(value: Suggestion[] | undefined);
    get suggestions(): Suggestion[];
    set filterSuggestions(value: Suggestion[] | undefined);
    get filterSuggestions(): Suggestion[];
    placeholder?: string;
    filterPlaceholder: string;
    variant: `${IGDS_SEARCH_FIELD_VARIANTS}`;
    disabled: boolean;
    showClear?: boolean;
    clearable: boolean;
    voiceSearch: boolean;
    dir: string;
    filters: Filter[];
    showEmptyResultsMessage: boolean;
    private _suggestions;
    private _filterSuggestions;
    private _suggestionsProvided;
    handleDocumentMouseDown(event: MouseEvent): void;
    onAudioRecorderStop(event: Event): void;
    playAudio(audioFile: Blob): void;
    private resizeHandler;
    private _scrollHandler;
    private startScrollListener;
    private stopScrollListener;
    disconnectedCallback(): void;
    render(): import("lit").TemplateResult<1>;
    onApply(event: CustomEvent): void;
    getInputIcon(): string;
    getInputCssClasses(): DirectiveResult<typeof ClassMapDirective>;
    renderClearIcon({ ariaLabel, onClick, onKeyDown, tabIndex, }: {
        ariaLabel: string;
        onClick: (event: Event) => void;
        onKeyDown: (event: KeyboardEvent) => void;
        tabIndex?: number;
    }): import("lit").TemplateResult<1>;
    renderFirstPart(): import("lit").TemplateResult<1>;
    renderSecondPart(): import("lit").TemplateResult<1>;
    renderDividedSearchField(): import("lit").TemplateResult<1>;
    isLtrHero(): boolean;
    isRtlHero(): boolean;
    isLtlHero(): boolean;
    isRtlHeroWithDoubleEndPadding(): boolean;
    isLtlHeroWithDoubleEndPadding(): boolean;
    hasExtraEndPadding(): boolean | "";
    hasExtraDoubleEndPadding(dir: 'rtl' | 'ltr'): boolean | "";
    renderDefaultOrHeroSearchField(): import("lit").TemplateResult<1>;
    isRelevantKey(key: IGDS_EVENT_KEYS): boolean;
    handleEnterOrSpaceDown(key: IGDS_EVENT_KEYS, isLeftInputFocused?: boolean): boolean;
    handleEscapeDown(key: IGDS_EVENT_KEYS): void;
    getHighlightedIndex(key: IGDS_EVENT_KEYS, suggestions: HTMLElement[], highlightedSuggestion: HTMLElement | undefined): number;
    processHighlightedIndex(suggestions: HTMLElement[], highlightedSuggestion: HTMLElement | undefined, index: number): void;
    handleArrowKeysDown(key: IGDS_EVENT_KEYS): void;
    onKeyDown(event: KeyboardEvent, isLeftInputFocused?: boolean): void;
    setValue(selectedSuggestion: Suggestion, isLeftInputFocused?: boolean): void;
    private getSearchSuggestions;
    private calculateIndexIncrement;
    removeHighlightedClass(): void;
    toggleSuggestionPopupByFirstInput(): void;
    toggleSuggestionPopup(): void;
    setPopupPosition(popupId?: string): Promise<void>;
    onInput(event: Event): void;
    onFirstInputChange(event: Event): void;
    onLastInputChange(event: Event): void;
    onSearch(): void;
    onLastInputSearch(): void;
    getSuggestions(): Suggestion[];
    getSearchedSuggestions(value: string, suggestionType?: 'filter' | 'typical'): Suggestion[];
    getIconsAndAudioRecorderBox(): import("lit").TemplateResult<1>;
    getClearIcon(): import("lit").TemplateResult<1>;
    getSettingsIcon(): import("lit").TemplateResult<1>;
    onClearIconKeyDown(event: KeyboardEvent, isFirstInputCleared?: boolean): void;
    onClear(event: Event, isFirstInputCleared?: boolean): void;
    onFilterIconKeyDown(event: KeyboardEvent): void;
    onFilterToggle(event: Event): void;
    getSearchIconButton(): import("lit").TemplateResult<1>;
    getAudioRecorder(): import("lit").TemplateResult<1>;
    renderSuggestions(): import("lit").TemplateResult<1>;
    setDividedSearchInputValue(suggestion: Suggestion): void;
    onSelect(suggestion: Suggestion): void;
    getSettingsIconTabIndex(): number;
    private getIconTabIndex;
}
export { SearchField };
declare global {
    interface HTMLElementTagNameMap {
        'igds-search-field': SearchField;
    }
}
