import { AngularFormElement } from '../abstractions';
import { PropertyValues } from 'lit';
import { IGDS_RATING_VARIANTS } from './constants';
import '../icon';
declare class Rating extends AngularFormElement {
    static formAssociated: boolean;
    private _internals;
    constructor();
    static styles: import("lit").CSSResult;
    componentId: string;
    dir: string;
    variant: `${IGDS_RATING_VARIANTS}`;
    readonly: boolean;
    label: string;
    ratingGrade: string[];
    name?: string;
    form?: string;
    onChange?: ((event: Event) => void) | null;
    isHovering: boolean;
    hoverValue: number;
    iconMaxCount: number;
    highlightedIndex: number | null;
    selectedIndex: number | null;
    ratingGroup: HTMLElement;
    ratingInput: HTMLInputElement;
    ratingButtons: HTMLButtonElement[];
    connectedCallback(): void;
    handleDocumentMouseDown(event: MouseEvent): void;
    updated(_changedProperties: PropertyValues): void;
    initializeRatingGrade(_changedProperties: PropertyValues): void;
    handleValuePropChange(_changedProperties: PropertyValues): void;
    render(): import("lit").TemplateResult<1>;
    onChangeHandler(event: Event): void;
    renderStarRatingButtons(): import("lit").TemplateResult<1>;
    getFaceButtonCssClasses(index: number): import("lit/async-directive.js").DirectiveResult<typeof import("lit/directives/class-map.js").ClassMapDirective>;
    getFaceIconCssClasses(index: number): import("lit/async-directive.js").DirectiveResult<typeof import("lit/directives/class-map.js").ClassMapDirective>;
    renderFaceRatingButtons(): import("lit").TemplateResult<1>;
    onMouseEnter(index: number): void;
    onMouseLeave(): void;
    onStarRatingClick(index: number): void;
    resetHighlightedSelection(): void;
    removeHighlightedClass(): void;
    onFaceRatingClick(grade: string, index: number): void;
    onFocus(event: Event): void;
    onKeyDown(event: KeyboardEvent): void;
    private handleTabKey;
    private getDirectionKeys;
    private isIncreaseKey;
    private isDecreaseKey;
    private handleIncrease;
    private handleDecrease;
    private updateValueForIncrease;
    private updateValueForDecrease;
    private updateHighlightedElement;
    commitSelection(): void;
    disconnectedCallback(): void;
}
export { Rating };
